name: setup
description: Scripts to set up configs and system environments.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  intl: ^0.18.1
  logger: ^1.3.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
